blogs/urls.py
from django.urls import path

from . import views

app_name = 'blogs'

urlpatterns = [
    path('', views.BlogHomeView.as_view(), name="home"),
    path('new/', views.NewBlogView.as_view(), name="new"),
    path('<uuid:uuid>/edit/', views.BlogEditView.as_view(), name="edit"),
    path('drafts/', views.BlogDraftView.as_view(), name="drafts"),
    path('<slug:slug>/', views.BlogReadView.as_view(), name="read"),
    path('<uuid:uuid>/publish/', views.BlogPublishView.as_view(), name="publish"),
    path('<uuid:uuid>/delete/', views.BlogDeleteView.as_view(), name="delete"),
    path('upvote/<uuid:uuid>/', views.UpvoteView.as_view(), name="upvote"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, reverse

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
]

blogs/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

User = getattr(settings, 'AUTH_USER_MODEL', 'auth.User')

class Post(models.Model):
    uuid = models.UUIDField(primary_key=True)
    author = models.CharField(max_length=256)
    slug = models.SlugField(max_length=256, unique=True, null=True)
    heading = models.CharField(max_length=512, null=True)
    content = models.TextField(null=True)
    is_published = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)
    published_on = models.DateTimeField(null=True)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self): # pragma: no cover
        return self.slug

    class Meta:
        get_latest_by = '-published_on'
        ordering = ('-published_on', '-created_on')


class Author(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        null=True)
    is_author = models.BooleanField(default=False)

    def __str__(self): # pragma: no cover
        return self.user.username

class Upvote(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE
    )
    fingerprint = models.CharField(max_length=128)
    is_upvoted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self): # pragma: no cover
        return "{}:{}".format(
            self.post.slug,
            self.fingerprint
        )

    class Meta:
        unique_together = ('post', 'fingerprint')
        ordering = ('-created_at',)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """
    Create an author on user creation
    """
    if created:
        Author.objects.create(user=instance)
    instance.author.save()

blogs/views.py
import uuid

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.http import HttpResponse, JsonResponse
from django.utils.text import slugify
from django.utils import timezone

from .models import Post, Upvote
from .mixins import AuthorRequiredMixin
from .settings import settings as app_settings

common_context = {
    'settings': app_settings
}


class BlogHomeView(View):
    
    def get(self, request):
        posts_list = Post.objects.filter(is_deleted=False, is_published=True)
        paginator = Paginator(posts_list, 15)

        page = request.GET.get('page')
        posts = paginator.get_page(page)
        return render(request, 'django-blogs/home.html', {
            'posts': posts,
            **common_context,
        })

class NewBlogView(LoginRequiredMixin, AuthorRequiredMixin, View):

    def get(self, request):
        post = Post.objects.create(
            author=request.user.username,
            uuid=uuid.uuid4(),
            heading="",
            content=""
        )
        return redirect('blogs:edit', uuid=post.uuid)

class BlogEditView(LoginRequiredMixin, AuthorRequiredMixin, View):

    def get(self, request, uuid):
        post = get_object_or_404(Post, pk=uuid)
        if not post.author == request.user.username:
            raise PermissionDenied
        return render(request, 'django-blogs/editor.html', {
            'blog': post,
            **common_context,
        })
    
    def post(self, request, uuid):
        if not all([key in request.POST for key in ['heading', 'content']]):
            return JsonResponse(
                {
                    'error': "'heading' and 'content' required"
                },
                status=400)
        post = get_object_or_404(Post, pk=uuid)
        if not post.author == request.user.username:
            raise PermissionDenied
        post.heading = request.POST['heading']
        post.slug = '-'.join([
            slugify(request.POST['heading'])[:200],
            post.uuid.hex[:12]
        ])
        post.content = request.POST['content']
        post.save()
        return HttpResponse(status=200)

class BlogDraftView(LoginRequiredMixin, AuthorRequiredMixin, View):

    def get(self, request):
        posts_list = Post.objects.filter(
            author__exact=request.user.username,
            is_deleted=False,
            is_published=False)
        paginator = Paginator(posts_list, 15)

        page = request.GET.get('page')
        posts = paginator.get_page(page)
        return render(request, 'django-blogs/drafts.html', {
            'posts': posts,
            **common_context,
        })

class BlogReadView(View):

    def get(self, request, slug):
        post = get_object_or_404(
            Post,
            slug=slug,
            is_deleted=False,
            is_published=True)
        upvote_count = post.upvote_set.filter(is_upvoted=True).count()
        return render(request, 'django-blogs/blog.html', {
            'post': post,
            'upvote_count': upvote_count,
            **common_context
        })

class BlogPublishView(LoginRequiredMixin, AuthorRequiredMixin, View):

    def get(self, request, uuid):
        post = get_object_or_404(Post, pk=uuid)
        if not post.author == request.user.username:
            raise PermissionDenied
        post.is_published = True
        post.published_on = timezone.now()
        post.slug = '-'.join([
            slugify(post.heading)[:200],
            post.uuid.hex[:12]
        ])
        post.save()
        return redirect("blogs:read", slug=post.slug)

class BlogDeleteView(LoginRequiredMixin, AuthorRequiredMixin, View):

    def get(self, request, uuid):
        post = get_object_or_404(Post, pk=uuid)
        if not post.author == request.user.username:
            raise PermissionDenied
        post.is_deleted = True
        post.save()
        return redirect("blogs:home")

class UpvoteView(View):

    def get(self, request, uuid):
        data = request.GET
        if not data.get('fingerprint', ''):
            return HttpResponse(status=400)
        upvote, created = Upvote.objects.get_or_create(
            post_id=uuid,
            fingerprint=data['fingerprint']
        )
        return JsonResponse(
            {
            'is_upvoted': upvote.is_upvoted
            },
            status=200
        )

    def post(self, request, uuid):
        data = request.POST
        if not data.get('fingerprint', ''):
            return HttpResponse(status=400)
        upvote, created = Upvote.objects.get_or_create(
            post_id=uuid,
            fingerprint=data['fingerprint']
        )
        upvote.is_upvoted = not upvote.is_upvoted
        upvote.save()
        return HttpResponse(status=200)

blogs/templates/django-blogs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
        {% block title %}
        <title>
            {% if settings.PARENT_SITE_NAME %}
            {{ settings.PARENT_SITE_NAME }} -
            {% endif %} Blogs
        </title>
        {% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/blogs-common.css'%}">
</head>

<body>

    <header class="mb-3 border-bottom">
        <div class="container">
            <div class="row pt-2">
                <div class="col">
                    <h5><a class="text-dark" href="{% url 'blogs:home' %}" style="text-decoration: none">Blogs</a></h5>
                </div>
                <div class="col">
                    <h5 class="text-center font-weight-bold"><a class="text-dark" href="/" style="text-decoration: none">{{settings.PARENT_SITE_NAME}}</a></h5>
                </div>
                <div class="col">
                    {% if user.is_authenticated %}
                    <div class="dropdown float-right">
                        <a class="h5 text-secondary" href="#" role="button" id="optionsDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-bars"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="optionsDropdown">
                            <a class="dropdown-item" href="{% url 'blogs:new' %}">New Post</a>
                            <a class="dropdown-item" href="{% url 'blogs:drafts' %}">Drafts</a>
                            {% block dropdown_options %}
                            {% endblock %}
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </header>

    <main class="container">
        {% if messages %}
        <div class="alert alert-success alert-dismissible" role="alert">
            {% for message in messages %}
            {{ message }}<br>
            {% endfor %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endif %}

    {% block content %} {% endblock %}
    </main>

    <footer class='footer mt-3 border-top'>
        {% include 'django-blogs/footer.html' %}
    </footer>

    {% if settings.GA_TRACKING_ID %}
        {% include 'django-blogs/google_analytics.html' %}
    {% endif %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>  

    {% block scripts %}
    <!-- block to add your own scripts -->
    {% endblock %}

</body>
</html>

blogs/templates/django-blogs/blog.html
{% extends 'django-blogs/base.html' %}

{% block dropdown_options %}
{% if post.author == user.username %}
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'blogs:edit' post.uuid %}">Edit</a>
    <a class="dropdown-item text-danger" href="{% url 'blogs:delete' post.uuid %}" style="opacity: 0.7">Delete</a>
{% endif %}
{% endblock %}

{% block content %}

<div class="position-fixed mt-5 ml-5 d-none d-lg-block">
    <div class="upvote-btn text-center">
        <p class="my-0 py-0"><i class="far fa-heart heart"></i></p>
        <p class="upvote-count">{{upvote_count}}</p>
    </div>
    <p class="mt-5 text-center"><i class="far fa-bookmark"></i></p>
    <p class="text-center"><i class="fas fa-share-alt"></i></p>
</div>
<div class="mt-5">
    <div class="row" style="max-width: 700px !important;margin: auto">
        <h1>{{ post.heading | safe }}</h1>
    </div>
    <div class="row mb-5" style="max-width: 700px !important;margin: auto">
        <div class="col-6 col-md-3 px-0">
            <i class="far fa-calendar-alt"></i> {{ post.published_on | date:"DATE_FORMAT" }}
        </div>
        <div class="col-6 col-md-3 px-0">
            <i class="fa fa-user"></i></i> {{post.author}}
        </div>
    </div>
    <div class="content">{{ post.content | safe }}</div>
    <div class="position-fixed float-left">
        Stick it somewhere
    </div>
    <div class="d-lg-none row mt-5 pt-2 border-top justify-content-center" style="max-width: 700px !important;margin: auto">
        <div class="col">
            <p class="upvote-btn"><i id="heart" class="far fa-heart heart"></i> <span class="upvote-count">{{upvote_count}}</span></p>
        </div>
        <div class="col">
            <p class="float-right ml-3"><i class="far fa-bookmark"></i></p>
            <p class="float-right ml-3"><i class="fas fa-share-alt"></i></p>
        </div>
    </div>
</div>

{% endblock %}

{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/fingerprintjs2/2.0.3/fingerprint2.js"></script>
<script>
var upvote_count = {{upvote_count}}
var add_upvote = true
$(".upvote-btn").click((event) => {
    Fingerprint2.get(function(components) {
        var fingerprint = Fingerprint2.x64hash128(components.map(function (pair) { return pair.value }).join(), 31)
        $.ajax({
            url: "{% url 'blogs:upvote' post.uuid %}",
            method: "POST",
            headers: {
                'X-CSRFToken': "{{ csrf_token }}"
            },
            success: (response) => {
                $(".heart").toggleClass('far').toggleClass('fas').html()
                if(add_upvote){
                    upvote_count += 1
                    $(".upvote-count").html(upvote_count)
                    add_upvote = false
                }
                else{
                    upvote_count -= 1
                    $(".upvote-count").html(upvote_count)
                    add_upvote = true
                }
            },
            data: {
                'fingerprint': fingerprint,
            }
        })
        return false
    })
})

$('document').ready(() => {
    Fingerprint2.get(function(components) {
        var fingerprint = Fingerprint2.x64hash128(components.map(function (pair) { return pair.value }).join(), 31)
        $.ajax({
            url: "{% url 'blogs:upvote' post.uuid %}",
            method: "GET",
            headers: {
                'X-CSRFToken': "{{ csrf_token }}"
            },
            success: (response) => {
                if(response.is_upvoted){
                    $(".heart").toggleClass('far').toggleClass('fas').html()
                    add_upvote = false
                }
            },
            data: {
                'fingerprint': fingerprint,
            }
        })
    })
})
</script>
{% endblock %}

blogs/templates/django-blogs/drafts.html
{% extends 'django-blogs/base.html' %}

{% block content %}

{% for post in posts %}
<a class="text-dark" href="{% url 'blogs:edit' post.uuid %}" style="text-decoration: none">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title"><strong>{{ post.heading | safe}}</strong></h4>
        </div>
    </div>
</a>
{% endfor %}

<div class="mt-2">
    <ul class="pagination justify-content-center pagination-sm">
        {% if posts.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ posts.previous_page_number }}">previous</a>
            </li>
        {% endif %}

        {% if posts.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ posts.next_page_number }}">next</a>
        </li>
        {% endif %}
    </ul>
</div>

{% endblock %}

blogs/templates/django-blogs/editor.html
{% extends 'django-blogs/base.html' %}

{% load static %}

{% block dropdown_options %}
<div class="dropdown-divider"></div>
<button onclick="saveData()" class="dropdown-item">Save</button>
{% if blog.is_published %}
    <a class="dropdown-item disabled" href="{% url 'blogs:publish' blog.uuid %}">Published</a>
    {% else %}
    <a class="dropdown-item" href="{% url 'blogs:publish' blog.uuid %}">Publish</a>
{% endif %}
<a class="dropdown-item text-danger-50" href="{% url 'blogs:delete' blog.uuid %}">Delete</a>
{% endblock %}

{% block content %}
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
<link rel="stylesheet" href="{% static 'css/beagle-theme.min.css' %}" type="text/css" media="screen">
<style>
    .editable {
        outline: none;
    }
    .editable p{
        font-size: 1.25rem;
    }
</style>

{% csrf_token %}

<div class="mt-5">
    <div class="row mb-5">
        <div class="col">
            <h1 class="editable" id="heading" data-placeholder="Title" style="max-width: 700px !important;margin: auto">{{ blog.heading | safe}}</h1>
        </div>
    </div>
    <div id="content" class="content editable medium-editor-element" data-placeholder="Write your post...">{{ blog.content | safe }}</div>
</div>

{% endblock %}

{% block scripts %}
<script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
<script>
    var typing;
    var editor = new MediumEditor('.editable', {
        buttonLabels: 'fontawesome',
        toolbar: {
            buttons: ['bold', 'italic', 'underline', 'anchor', 'h2', 'h3', 'html']
        },
        autoLink: true,
    });

    editor.subscribe('editableInput', function (event, editable) {
        clearTimeout(typing); //
        typing = setTimeout(saveData, 2000) // try to save data when user stops for 2 second
    });


    var saveData = function(){
        var csrftoken = $('[name=csrfmiddlewaretoken').val();
        var subtitle = $('#content').find('p').first().text();
        var content = {
            'heading': $('#heading').html(),
            'content': $('#content').html(),
        }        
        
        $.ajax({
            url: "{% url 'blogs:edit' blog.uuid%}",
            method: "post",
            data: content,
            headers: {
                'X-CSRFToken': csrftoken
            }
        })
    }
</script>
{% endblock %}

blogs/templates/django-blogs/footer.html
<div align="center">
    {% if settings.SHOW_FOOTER_LINK %}
    <small>Powered by <a href="https://github.com/arjunsinghy96/django-blogs">django-blogs</a></small>
    {% endif %}
</div>

blogs/templates/django-blogs/google_analytics.html
<!-- Global Site Tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id={{settings.GA_TRACKING_ID}}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '{{settings.GA_TRACKING_ID}}');
</script>

blogs/templates/django-blogs/home.html
{% extends 'django-blogs/base.html' %}

{% block content %}

{% for post in posts %}
<a class="text-dark" href="{% url 'blogs:read' post.slug %}" style="text-decoration: none">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title"><strong>{{ post.heading | safe}}</strong></h4>
            <div class="row">
                <div class="col-12 col-md-2">
                    <i class="far fa-calendar-alt"></i> {{ post.published_on | date:"DATE_FORMAT" }}
                </div>
                <div class="col-12 col-md-3">
                    <i class="fa fa-user"></i></i> {{post.author}}
                </div>
            </div>
        </div>
    </div>
</a>
{% endfor %}

<div class="mt-2">
    <ul class="pagination justify-content-center pagination-sm">
        {% if posts.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ posts.previous_page_number }}">previous</a>
            </li>
        {% endif %}

        {% if posts.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ posts.next_page_number }}">next</a>
        </li>
        {% endif %}
    </ul>
</div>

{% endblock %}